services:
  devenv:
    build:
      context: .
      target: final
      secrets:
        - github_personal_access_token
    container_name: devenv
    entrypoint: /bin/bash
    ports:
      - 8888:8888
    secrets:
      - github_personal_access_token
    stdin_open: true
    tty: true
    user: dave
    volumes:
      - ~/.ssh:/home/dave/.ssh
      - ../code:/home/dave/code

secrets:
  github_personal_access_token:
    environment: GH_TOKEN
