services:
  devenv:
    build:
      context: .
      target: final
    container_name: devenv
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - ../code:/home/dave/code
